version: "3.8"
services:
  app:
    image: node:16
    container_name: node_app
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8081:8081"
      - "1000:1000"
    environment:
      - NODE_ENV=development
